### ISSUE TITLE
Syncthing installed on OS5 but cannot access at port 8384

### ISSUE THREAD

**Issue by suspiration** [WDCommunity/wdpksrc#100]
**Platform**
My Cloud OS5 on WD EX2 Ultra

**Application**
Syncthing 1.11.1

**Describe the bug**
I was able to install syncthing successfully, but when I tried to click the "Configure" button from the app. It opens a new tab to  http://192.168.1.2:8384, but it does not resolve.  Checked system log and did not see anything error.  Tried turning app off and on again, as well as uninstalling and reinstalling, but nothing works.  Any help would be greatly appreciated!

**Comment by herrxyz** [comment]
got same problem, webinterface not accessible anymore, as far as I remember the problem is since last update (or maybe the update before that, didn't check syncthing). currently I'm at OS 5.18.117 on my mycloudex2ultra

**Comment by herrxyz** [comment]
solved my problem by uninstalling syncthing, deleting folders using ssh and reinstalling new compiled version 1.18. ..

**Comment by suspiration** [comment]
same, i had to ssh and delete the syncthing folders, then reinstalling works.

**Comment by codefreak558** [comment]
Hi I am getting the same issue but I don't know what folders I need to delete

**Comment by city3k5** [comment]
> Putting it here so others don't have to figure it out like I had to:
> 
> Path to the OS5 apps data / configs / binaries / etc, seems to generally be: **`/mnt/HD/HD_a2/Nas_Prog/[PACKAGE_NAME]`**
> 
> If you need to purge app data, it should suffice to delete appropriate folders from the mentioned path.

Could you please write which commands are used to get to the folder and which ones are used to delete it?

**Comment by codefreak558** [comment]
1. cd /mnt/HD/HD_a2/Nas_Prog/
2. rm -r [PACKAGE_NAME]

Once those commands are done then the package you wanted to delete will be deleted.
