### ISSUE TITLE
update syncthing please

### ISSUE THREAD

**Issue by herrxyz** [WDCommunity/wdpksrc#101]
hello,
is it possible to update syncthing? current version is "Syncthing v1.18.4", download on https://wdcommunity.com/ is 1.3.0 (for mycloudex2ultra)

I dont know how, but on my mycloudex2ultra synchting is 1.11.1 (and not asscessible using browser on http://192.168.178.32:8384/ , maybe same problem as [#100](https://github.com/WDCommunity/wdpksrc/issues/100).

**Comment by herrxyz** [comment]
after self compiling 1.18.4 and installing it to a new mycloudex2ultra, it seems to work.
only bad thing is " 2021-12-04 13:59:20: Syncthing should not run as a privileged or system user. Please consider using a normal user account. "

**Comment by herrxyz** [comment]
sent pull request

**Comment by ASaphala** [comment]
I encountered the same issues with the latest version (1.20.2). Could you tell me how you install Syncthing?
I followed the instruction on how to create the bin file from [here ](https://community.wd.com/t/syncthing-with-os5/266713/14).
However, when I tried to compile the older version (1.11.1 and 1.18.4) it seems the binary I generated is different from what is available.
Am I missing something? Should I try to install Syncthing directly on the NAS via ssh?
