### ISSUE TITLE
Syncthing not avalible on port 8384

### ISSUE THREAD

**Issue by codefreak558** [WDCommunity/wdpksrc#115]
**Platform**
WDMyCloudEX2

**Application**
Syncthing 1.3.0

**Describe the bug**
I had syncthing installed and working fine for around a day then the next day when I wanted to start using it and syncing between different machene I couldn't. It gave me `IP refused to connect.` I have tried reinstalling the app with no luck.

There seems to have been a solution #100 but I don't know where the folders they are mentioning are stored. From my very brief look though the file system I dont find anything mentioning apps or syncthing hence not knowing what to try removing to start from fresh. This seems to be happening with any apps I install as I also tried installing duplacati to no avail. If it has any correlation I had Plex running for about a day as well when it also stopped working

**Comment by Msprg** [comment]
### **`/mnt/HD/HD_a2/Nas_Prog/[PACKAGE_NAME]`**
