### ISSUE TITLE
docker on EX4100 packages updated - docker-18.06.0-ce.tgz

### ISSUE THREAD

**Issue by JediNite** [WDCommunity/wdpksrc#14]
Hi,

I've updated the packages for docker on the EX4100 to docker-18.06.0-ce.tgz.  File is available at https://github.com/JediNite/docker-ce-WDEX4100-binaries/raw/master/armv7l-WDEX4100/docker-18.06.0-ce.tgz.

Cheers,

JediNite

**Comment by stefaang** [comment]
Thanks. I'll do a quick sanity check on the PR4100 next week and bump the version.

**Comment by stefaang** [comment]
Fixed with https://github.com/WDCommunity/wdpksrc/commit/211213a8c6144fc0c79d3eb6edc618eea2bcbd2b
