### ISSUE TITLE
[entware] install fails on MyCloudEX4

### ISSUE THREAD

**Issue by jaysquared2** [WDCommunity/wdpksrc#29]
Tried to install WDMyCloudEX4_entware_1.04.bin via webgui on my MyCloudEX4 and it seemed to install fine.

However, running opkg gives 'Illegal Instruction' error. Investigating further, it seems the install script is installing entware meant for armv7 devices. I think the EX4 is armv5?

uname -a on my device yields:
```
Linux WDMyCloudEX4 3.2.40 #1 Fri Nov 16 11:50:03 CST 2018 armv5tel GNU/Linux
```
Same thing with the docker package; I believe armv7 binary is installed so it fails in the same way.

**Comment by stefaang** [comment]
Thanks for your report.
What is the firmware version on your My Cloud EX4?
I will update the entware installer to pick the correct armv5 branch.

I'm not sure if docker is supported on armv5, so I may have to remove those builds.

**Comment by stefaang** [comment]
Any luck with this package?
[WDMyCloudEX4_entware_1.05.zip](https://github.com/WDCommunity/wdpksrc/files/2780738/WDMyCloudEX4_entware_1.05.zip)

**Comment by stefaang** [comment]
BTW, I had already removed the MyCloud, EX2 and EX4 docker binaries from the website. Did I forget to clean up somewhere else?

**Comment by jaysquared2** [comment]
I can confirm 1.05 works. I've installed several packages with opkg and they all persisted through a reboot. This issue can be closed.

My EX4 version is 2.12.127.

Docker v18.03.1 for MyCloud, EX2 and EX4 can still be downloaded from the github release page.

Awesome work btw. Now my EX4 is infinitely more useful. Thank you!

**Comment by stefaang** [comment]
Thanks for the feedback, I'll add a fix for another upgrade issue and then release the 1.05 packages.
