### ISSUE TITLE
[docker] [single bay mycloud] error initializing network controller

### ISSUE THREAD

**Issue by gotschi** [WDCommunity/wdpksrc#32]
i get this error when i start docker:

Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER: iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)

What can I do about it? Is there a newer kernel for this device?

**Comment by stefaang** [comment]
What is the output of `uname -r`? The devices with a 3.2 kernel (EX2, EX4) can't run docker.. 
I may need to remove the single bay mycloud from the list as well.

**Comment by stefaang** [comment]
Thanks.. that looks fine actually.
Have you tried to reboot?
Eventually, provide the output of this script: https://github.com/moby/moby/blob/master/contrib/check-config.sh

**Comment by gotschi** [comment]
Yes I've tried rebooting and running scripts manually,
here's the output: https://pastebin.com/ATaUprSc

**Comment by stefaang** [comment]
Here's my output
```
lsmod | grep tables
ip6_tables 15873 1 ip6table_filter, Live 0xffffffffc0359000
ip_tables 15171 2 iptable_nat,iptable_filter, Live 0xffffffffc033f000
x_tables 15016 13 ipt_MASQUERADE,xt_nat,xt_addrtype,ip6table_filter,ip6_tables,iptable_filter,ip_tables,xt_limit,xt_LOG,xt_recent,xt_tcpudp,xt_state,xt_conntrack, Live 0xffffffffc0303000
```
Which IP related kernel modules do you have available in your firmware? I have this
```
ls /usr/local/modules/driver/ip*
/usr/local/modules/driver/ip6_tables.ko       /usr/local/modules/driver/ip_tables.ko        /usr/local/modules/driver/ipt_MASQUERADE.ko   /usr/local/modules/driver/ipv6.ko
/usr/local/modules/driver/ip6_tunnel.ko       /usr/local/modules/driver/ip_tunnel.ko        /usr/local/modules/driver/iptable_filter.ko
/usr/local/modules/driver/ip6table_filter.ko  /usr/local/modules/driver/ipip.ko             /usr/local/modules/driver/iptable_nat.ko
```
I see you don't have the `iptable_nat.ko` as I do.
```
lsmod | grep nat
iptable_nat 1599 1 - Live 0xffffffffc0420000
nf_nat_masquerade_ipv4 1729 1 ipt_MASQUERADE, Live 0xffffffffc040c000
xt_nat 1809 0 - Live 0xffffffffc0408000
nf_nat_ipv4 4543 1 iptable_nat, Live 0xffffffffc03ee000
nf_nat 10637 3 nf_nat_masquerade_ipv4,xt_nat,nf_nat_ipv4, Live 0xffffffffc03dd000
ip_tables 15171 2 iptable_nat,iptable_filter, Live 0xffffffffc033f000
nf_conntrack 50279 7 nf_nat_masquerade_ipv4,nf_nat_ipv4,nf_nat,nf_conntrack_ipv6,nf_conntrack_ipv4,xt_state,xt_conntrack, Live 0xffffffffc030c000
x_tables 15016 13 ipt_MASQUERADE,xt_nat,xt_addrtype,ip6table_filter,ip6_tables,iptable_filter,ip_tables,xt_limit,xt_LOG,xt_recent,xt_tcpudp,xt_state,xt_conntrack, Live 0xffffffffc0303000
```
Worst case, you can snatch these kernel modules from the EX2 Ultra firmware (use binwalk to extract it).

**Comment by gotschi** [comment]
as you can see in the daemon logs there also seems to be no "overlay2" driver for this kernel,
I think that might even be a bigger problem :D 

`'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.  storage-driver=overlay`

i will stick to armhf on a rpi, thanks for your quick response anyway!

**Comment by stefaang** [comment]
Aight. You may want to install debian armhf instead of the WD firmware, but I'll leave that up to you.
I'll remove the MyCloud as a valid docker target.
Thanks for your report!

**Comment by gotschi** [comment]
I put debian on a seagate single bay device before,
it worked like a charm for over a year but then I've misconfigured something and couldn't get it to boot anymore. The Firmware was a tarball and needs to be installed via TFTP, but I have no clue how (Seagate does not provide a firmware flash utility and I don't know how the root is supposed to be written to the HD)

Could this also happen to the mycloud? Or is there some kind of Bootloader to always restore to WD Firmware?
