### ISSUE TITLE
Update Transmission PR4100

### ISSUE THREAD

**Issue by FayzB** [WDCommunity/wdpksrc#34]
Hello,
Can you tell me how to update Transmission on the WD PR4100 version of WD and the
version 1.06.bin Transmission 2.84 (14307).

**Comment by stefaang** [comment]
As my spksrc port is in usable state now, everything is in place to this with minimal effort... 

- checkout https://github.com/stefaang/spksrc
- add the xor_checksum binary to your PATH (or move it to /usr/local/bin)
- go to the directory of the project you want to build
```
cd spk/transmission
```
- create the x64 packages (PRx100, DLx100) with 
```
make apkg-wdx64
```
- create the other packages with
```
make apkg-wdarm
```
- the binaries are available here
```
cd ../../packages
```

Unfortunately it won't work right out of the box yet as we don't have a menu based installer like synocommunity has. Some changes will be required here:
https://github.com/stefaang/spksrc/blob/master/spk/transmission/src/service-setup.sh

If this is all a bit too much, [my old method](https://community.wd.com/t/package-entware-the-ultimate-repo-with-about-2000-packages/213711/2) is still a valid alternative.

**Comment by stefaang** [comment]
Once I'm done with the emby-mono port, I'll have a look at Transmission and alternatives.

**Comment by stefaang** [comment]
Here's a package you could use (unzip it first).
[transmission_PR4100_2.94-16.zip](https://github.com/WDCommunity/wdpksrc/files/2979246/transmission_PR4100_2.94-16.zip)
[transmission_PR2100_2.94-16.zip](https://github.com/WDCommunity/wdpksrc/files/2979247/transmission_PR2100_2.94-16.zip)

It's quite different to the original WD package so you'll have to reconfigure the settings.

**Comment by stefaang** [comment]
Latest packages available on https://bintray.com/tfl/wdpksrc
