### ISSUE TITLE
Docker Install on PR4100

### ISSUE THREAD

**Issue by akanoodles** [WDCommunity/wdpksrc#37]
So I’ve downloaded Docker install from https://wdcommunity.com/, but when I load it up on host:9000. I get Twonky Server and not Docker or Portainer. What is going on?

**Comment by akanoodles** [comment]
Hey @stefaang I tried both methods and still no luck.

**Comment by stefaang** [comment]
Please provide some more info

    netstat -tulpn | grep 9000
    docker ps

**Comment by akanoodles** [comment]
Sorry, I'm a noob at this, I have turned on SSH on my WD mycloud, setup a password. Used Terminal to try and ssh into the drive. But keep getting denied password. I also can't remove the original install of docker via the Web UI. reboot and it is always still there.

**Comment by stefaang** [comment]
Sorry, I can't help you to setup SSH access. Try searching the forum for a guide.

**Comment by akanoodles** [comment]
Ok, I'm in now
<img width="539" alt="Screenshot 2019-05-29 at 14 21 49" src="https://user-images.githubusercontent.com/1613697/58560503-2f419380-821d-11e9-8f56-7a0a89d7a036.png">

**Comment by stefaang** [comment]
Now try this
```
cd /shares/Volume_1/Nas_Prog/docker
docker run -d -p 9000:9000 --restart always \
     -v /var/run/docker.sock:/var/run/docker.sock \
     -v $(pwd)/portainer:/data portainer/portainer
```

**Comment by akanoodles** [comment]
<img width="841" alt="Screenshot 2019-05-29 at 14 36 19" src="https://user-images.githubusercontent.com/1613697/58561506-28b41b80-821f-11e9-9ec0-8774451df2f6.png">

**Comment by akanoodles** [comment]
Yeah so, that what my problem is that the bin file doesnt work on port 9000

**Comment by stefaang** [comment]
Right, you tried uninstalling, so the daemon is not initialized.
Remove docker.

    cd /shares/Volume_1/Nas_Prog
    del_apkg docker
    rm -rf _docker docker

Reinstall docker.

**Comment by akanoodles** [comment]
Awesome! Portainer now running!!!!

**Comment by akanoodles** [comment]
Thank you so much for your help, awesome work!

**Comment by stefaang** [comment]
np.

**Comment by mlbnc** [comment]
> Right, you tried uninstalling, so the daemon is not initialized.
> Remove docker.
> 
> ```
> cd /shares/Volume_1/Nas_Prog
> del_apkg docker
> rm -rf _docker docker
> ```
> 
> Reinstall docker.
> PS, you may just select the text and put it in code tags (triple backquote)

Hello, how do you reinstall docker pls ?

**Comment by stefaang** [comment]
You use those commands to delete docker.
Then upload the docker binary via WD web interface.

If anything went wrong, you could run the installer manually.

    cd /shares/Volume_1/Nas_Prog/docker

Disable the copy step

    sed -i 's@cp -rf@#cp -rf@' install.sh
    
Then run the installer

    ./install.sh . ..

If anything goes wrong, create a new ticket.

**Comment by latinoheat81** [comment]
hi someone could you tell me if it is possible to install Docker on wd my cloud 1 bay os5? if you can could you please tell me how to do it thanks in advance

**Comment by phyppe** [comment]
> Ok, I'm in now <img alt="Screenshot 2019-05-29 at 14 21 49" width="539" src="https://user-images.githubusercontent.com/1613697/58560503-2f419380-821d-11e9-8f56-7a0a89d7a036.png">

How do you get access I can't do it cause it says the password is wrong
