### ISSUE TITLE
docker on EX4100 packages updated - docker-19.03.2.tgz

### ISSUE THREAD

**Issue by JediNite** [WDCommunity/wdpksrc#42]
Hi,

I've updated the packages for docker on the EX4100 to docker-19.03.2. File is available at https://github.com/JediNite/docker-ce-WDEX4100-binaries/blob/master/armv7l-WDEX4100/docker-19.03.2.tgz.

Cheers,

JediNite

**Comment by stefaang** [comment]
Thanks again! See https://github.com/WDCommunity/wdpksrc/pull/43
