### ISSUE TITLE
duplicati package: start-stop-status needs rewrite due to busybox limitations

### ISSUE THREAD

**Issue by tonyrayo** [WDCommunity/wdpksrc#5]
Busybox v1.20.2 (current default for latest official PR4100 firmware) was not compiled with the `math` function, therefore on startup, when `start.sh` goes to launch `start-stop-status`, it errors out.

`line 102: syntax error: you disabled math support for $((arith)) syntax`

**Comment by stefaang** [comment]
Fixed the shebang here: https://github.com/WDCommunity/wdpksrc/commit/16004c791f93f01a54e87f7bcbface986bdb72c4
