### ISSUE TITLE
WD My Cloud Home

### ISSUE THREAD

**Issue by VismoDoc** [WDCommunity/wdpksrc#52]
Seems that WD My Cloud Home can run Debian: http://4pda.ru/forum/index.php?showtopic=467828&st=12140#entry87961189

**Comment by VismoDoc** [comment]
Also this is interesting regarding WD My Cloud Home: http://4pda.ru/forum/index.php?showtopic=467828&st=12100#entry87843378

**Comment by stefaang** [comment]
I'd have to look in my archives but indeed, it's possible to run Debian on MCH.
It requires a patch in the bootloader though.

**Comment by stefaang** [comment]
If you're able to translate to english, please feel free to update https://github.com/WDCommunity/wdpksrc/wiki/My-Cloud-Home

**Comment by VismoDoc** [comment]
I'm currently running Debian on it. Installation seems very easy but as I understand it isn't a "clean installation" like when you run the installer and it does its work, but it just extracts files from an archive and move them to the right place. Looks like they installed the os on a machine and then copied all files from the root directory and than created the archive.
