### ISSUE TITLE
Migrate "cops" to OS5

### ISSUE THREAD

**Issue by stephanmax** [WDCommunity/wdpksrc#62]
Hi there,
Any chance to get the cops package updated for OS5. I currently get the infamous "Incomplete App Download" error when trying to install the bin file manually.
Many thanks, Stephan

**Comment by MattMarchy** [comment]
+1

**Comment by stefaang** [comment]
https://bintray.com/beta/#/tfl/wdpksrc/COPS?tab=overview

**Comment by stephanmax** [comment]
Seems to have done the trick. Many thanks, Stefaan!
