### ISSUE TITLE
Migrate "tautulli" to OS5

### ISSUE THREAD

**Issue by kostasdrakonakis** [WDCommunity/wdpksrc#64]
Hi is there any chance that you will migrate tautulli to support OS5?I currently get the infamous "Incomplete App Download" error when trying to install the bin file manually.
Many thanks, Kostas

**Comment by navyseai** [comment]
+1

**Comment by stefaang** [comment]
Here you go https://bintray.com/beta/#/tfl/wdpksrc/Tautulli/2.6.1?tab=overview

**Comment by navyseai** [comment]
guess now i need to wait for entware for cloud ex2 ultra

**Comment by stefaang** [comment]
@navyseai look around a bit https://bintray.com/beta/#/tfl/wdpksrc/Entware?tab=overview
