### ISSUE TITLE
Containers can't talk to each other

### ISSUE THREAD

**Issue by akanoodles** [WDCommunity/wdpksrc#65]
Hardware: WD PR4100
OS: 5.04.114
Running: Docker with Portainer 1.24.1
Containers running:
linuxserver/Medusa
linuxserver/Transmission
linuxserver/deluge
linuxserver/Plex

Problem:
Medusa gets a connection error when trying to access the Transmission host: port (192.168.0.32 9091)
Seems like the containers can't talk to each other
How do I fix this within Portainer

Medusa 
![98545040-c329e280-228c-11eb-9858-07f2cb26794f](https://user-images.githubusercontent.com/1613697/98671751-a5bc4d80-234c-11eb-93c3-e494566e3bce.png)

Transmission
![98545087-d6d54900-228c-11eb-8c32-63805be88744](https://user-images.githubusercontent.com/1613697/98671754-a654e400-234c-11eb-8c4b-0b8a311d6ed7.png)

New Network
![Screenshot_2020-11-10 Portainer](https://user-images.githubusercontent.com/1613697/98672051-16636a00-234d-11eb-9dd3-db6de8752230.png)

I've tried to create a new bridge and still can't fix (unless I'm getting the settings wrong).

**Comment by JediNite** [comment]
@akanoodles 

The IP address range is different on the new network you created. If the containers are to talk internally to each other you need to do so using the IP addresses the containers have on that network.

Cheers

JediNite

**Comment by akanoodles** [comment]
@JediNite I'm a noob at doing this, are you able to provide an example of how to fix this?
![Screenshot_2020-11-11 Portainer](https://user-images.githubusercontent.com/1613697/98830883-cfe83b00-2432-11eb-9f90-d85a96ad46f8.png)

**Comment by akanoodles** [comment]
I figured it out, I just had to connect without creating a new network but targeting the IP address that Portainer created instead of my localhost IP
