### ISSUE TITLE
mc also for other systems?

### ISSUE THREAD

**Issue by zackdvd** [WDCommunity/wdpksrc#83]
Hi, do you plan to release mc also for e.g. EX2 Ultra? 
Currently on bintray only the following version is available:
mc_**PR4100**_4.8.21-5.bin

Thank you!

Best,
Zack

**Comment by stefaang** [comment]
You can install it via the entware package.

**Comment by zackdvd** [comment]
Oh wow, only had contact with opkg some years ago and didn't had the connection that it's called entware.

Thanks, will do some charity donation in your name for your great work
 :-)
