### ISSUE TITLE
What would happen if someone created an `entware` share in either OS3 or OS5? Potential problem?

### ISSUE THREAD

**Issue by Myron-S** [WDCommunity/wdpksrc#88]
Just a thought. I'm not going to do this on my NAS has al hell may break loose, but in the quest to protect other users from themselves I ask a question . . . .

The actual _entware_ directory is stored in `/shares/Volume_1/entware/`.

What would happen if someone was to create a network share named _entware_ through WD's dashboard UI?

Is it possible for the OS3 and OS5 installers to name the _entware_ folder as `/shares/Volume_1/.entware/`?  Could an WD _entware_ app update be put together that would perform such a rename and remount `/opt` from `/shares/Volume_1/entware/` to `/shares/Volume_1/.entware/`.

Should work as nothing should be writing directly to the proposed `/shares/Volume_1/.entware/` or `/mnt/HD/HD_a2/entware`, but only to `/opt`.

**Comment by stefaang** [comment]
It's about as likely as creating a `Nas_Prog` share.
Nobody stops you from doing it but it's not something I'd bother about.

**Comment by Myron-S** [comment]
Good point, but I'm guessing WD would have put something in the dashboard UI to reject `Nas_progs` as a share name. Still, anyone who wishes to use entware should really know better and not try.  :-)
